# Generated by Django 6.0.3 on 2026-04-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_menubuilder', '0002_menuitem_parent'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_dropdown',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(help_text='Unique identifier used to render this menu in templates.', unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(help_text='Menu title.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='internal_link',
            field=models.ForeignKey(blank=True, help_text='Internal page link. Overrides external URL if set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_links', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set a parent item to create a dropdown. Must belong to the same menu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wagtail_menubuilder.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(help_text='Text displayed in the menu.', max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.URLField(blank=True, help_text='External URL. Leave blank if using an internal page link or this is a dropdown parent.', null=True),
        ),
    ]
